### ISSUE TITLE
builtin cd, export, unset 문제

### ISSUE THREAD

**Issue by 42joonpark** [42joonpark/minishell#25]
**cd 명령어를 실행해도 디렉토리가 바뀌지 않는 문제 발생.**
1. 지금 child process에서 builtin을 실행함.
2. 만약 cd builtin 명령어를 실행하면 child process에서 working directory를 이동함.
3. 그리고 child process 종료
4. parent process 입장에서는 working directory 가 바뀌지 않음

그래서 cd 명령어를 실행해도 디렉토리가 바뀌지 않는 문제 발생.

**Comment by pdh9311** [comment]
cd 명령어 뿐 아니라 export, unset 명령어도 parent process의 전역변수에 저장된 값을 수정해주어야 하는 상황이 있기 때문에,
 parent process에서 실행 해줄 필요가 있어 보임.

**Comment by 42joonpark** [comment]
cd, export, unset 을 따로 처리하도록 변경 완료.
