### ISSUE TITLE
env > [filename] 안됨.

### ISSUE THREAD

**Issue by 42joonpark** [42joonpark/minishell#26]
path$ env > res 실행 시
아무것도 출력이 안되고 env 내용이 res 에 저장되야 하는데
env 내용이 출력되고 res에는 아무것도 없음.

**Comment by pdh9311** [comment]
![2021-11-13](https://user-images.githubusercontent.com/42412663/141506299-7704d1d4-63a5-4907-9a3d-f9f9ecee5937.png)
저한테서는 evn > [file] 실행이 정상적으로 되는데, 내일 확인해 봐야할거 같네요.

**Comment by 42joonpark** [comment]
잘 된다.
